spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: sa
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none